name: sensors_monitoring
description: Service for monitoring sensors. Student project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  fluent_ui: ^4.7.7
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^12.1.0
  injectable: ^2.3.1
  provider: ^6.0.5
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  mockito: ^5.4.2

flutter:
  uses-material-design: false
